/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectController_listMine"];
        put?: never;
        post: operations["ProjectController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ProjectController_remove"];
        options?: never;
        head?: never;
        patch: operations["ProjectController_update"];
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProfileController_findMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ProfileController_updateMine"];
        trace?: never;
    };
    "/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PortfolioController_find"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TokenDto: {
            token: string;
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        CredentialSummaryDto: {
            userId: number;
            /** Format: date-time */
            createdAt: string;
        };
        RegisterDto: {
            username: string;
            /** Format: email */
            email: string;
            password: string;
        };
        ProjectAssetDto: {
            /** @enum {string} */
            kind: "repository" | "demo" | "image" | "video" | "doc";
            /** Format: uri */
            url: string;
            label: string | null;
            position: number;
        };
        ProjectDto: {
            id: number;
            userId: number;
            slug: string;
            title: string;
            description: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            endedAt: string | null;
            published: boolean;
            position: number;
            assets: components["schemas"]["ProjectAssetDto"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateProjectDto: {
            slug: string;
            title: string;
            description?: string | null;
            startedAt?: string | null;
            endedAt?: string | null;
            published?: boolean;
            position?: number;
            assets?: components["schemas"]["ProjectAssetDto"][];
        };
        UpdateProjectDto: {
            slug: string;
            title: string;
            description?: string | null;
            startedAt?: string | null;
            endedAt?: string | null;
            published?: boolean;
            position?: number;
            assets?: components["schemas"]["ProjectAssetDto"][];
        };
        ProfileLinkDto: {
            /** @enum {string} */
            kind: "github" | "linkedin" | "web" | "email" | "other";
            /** Format: uri */
            url: string;
            label: string | null;
            position: number;
        };
        ProfileDto: {
            id: number;
            userId: number;
            fullName: string;
            headline: string | null;
            bio: string | null;
            location: string | null;
            publicEmail: string | null;
            avatarUrl: string | null;
            links: components["schemas"]["ProfileLinkDto"][];
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateProfileDto: {
            fullName?: string;
            headline?: string | null;
            bio?: string | null;
            location?: string | null;
            /** Format: email */
            publicEmail?: string | null;
            /** Format: uri */
            avatarUrl?: string | null;
            links?: components["schemas"]["ProfileLinkDto"][];
        };
        PortfolioDto: {
            username: string;
            profile: components["schemas"]["ProfileDto"];
            projects: components["schemas"]["ProjectDto"][];
        };
        ApiErrorDetailDto: {
            /** @example email */
            field?: string;
            /** @example email must be an email */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 200 */
                        code: number;
                        data: components["schemas"]["TokenDto"];
                        /** @example Operation successful */
                        message: string;
                        /** @example null */
                        errors: null;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 500 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example Internal server error */
                        message: string;
                        /** @example null */
                        errors: components["schemas"]["ApiErrorDetailDto"][] | null;
                    };
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 201 */
                        code: number;
                        data: components["schemas"]["CredentialSummaryDto"];
                        /** @example Resource created */
                        message: string;
                        /** @example null */
                        errors: null;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 500 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example Internal server error */
                        message: string;
                        /** @example null */
                        errors: components["schemas"]["ApiErrorDetailDto"][] | null;
                    };
                };
            };
        };
    };
    ProjectController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 200 */
                        code: number;
                        data: components["schemas"]["ProjectDto"][];
                        /** @example Operation successful */
                        message: string;
                        /** @example null */
                        errors: null;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 500 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example Internal server error */
                        message: string;
                        /** @example null */
                        errors: components["schemas"]["ApiErrorDetailDto"][] | null;
                    };
                };
            };
        };
    };
    ProjectController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 201 */
                        code: number;
                        data: components["schemas"]["ProjectDto"];
                        /** @example Resource created */
                        message: string;
                        /** @example null */
                        errors: null;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 500 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example Internal server error */
                        message: string;
                        /** @example null */
                        errors: components["schemas"]["ApiErrorDetailDto"][] | null;
                    };
                };
            };
        };
    };
    ProjectController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 200 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example Project deleted */
                        message: string;
                        /** @example null */
                        errors: null;
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 404 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example Project not found */
                        message: string;
                        /** @example null */
                        errors: components["schemas"]["ApiErrorDetailDto"][] | null;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 500 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example Internal server error */
                        message: string;
                        /** @example null */
                        errors: components["schemas"]["ApiErrorDetailDto"][] | null;
                    };
                };
            };
        };
    };
    ProjectController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 200 */
                        code: number;
                        data: components["schemas"]["ProjectDto"];
                        /** @example Operation successful */
                        message: string;
                        /** @example null */
                        errors: null;
                    };
                };
            };
            /** @description You cannot modify this project */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 403 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example You cannot modify this project */
                        message: string;
                        /** @example null */
                        errors: components["schemas"]["ApiErrorDetailDto"][] | null;
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 404 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example Project not found */
                        message: string;
                        /** @example null */
                        errors: components["schemas"]["ApiErrorDetailDto"][] | null;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 500 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example Internal server error */
                        message: string;
                        /** @example null */
                        errors: components["schemas"]["ApiErrorDetailDto"][] | null;
                    };
                };
            };
        };
    };
    ProfileController_findMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 200 */
                        code: number;
                        data: components["schemas"]["ProfileDto"];
                        /** @example Operation successful */
                        message: string;
                        /** @example null */
                        errors: null;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 500 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example Internal server error */
                        message: string;
                        /** @example null */
                        errors: components["schemas"]["ApiErrorDetailDto"][] | null;
                    };
                };
            };
        };
    };
    ProfileController_updateMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 200 */
                        code: number;
                        data: components["schemas"]["ProfileDto"];
                        /** @example Operation successful */
                        message: string;
                        /** @example null */
                        errors: null;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 500 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example Internal server error */
                        message: string;
                        /** @example null */
                        errors: components["schemas"]["ApiErrorDetailDto"][] | null;
                    };
                };
            };
        };
    };
    PortfolioController_find: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 200 */
                        code: number;
                        data: components["schemas"]["PortfolioDto"];
                        /** @example Operation successful */
                        message: string;
                        /** @example null */
                        errors: null;
                    };
                };
            };
            /** @description No portfolio has been set up yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 404 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example No portfolio has been set up yet */
                        message: string;
                        /** @example null */
                        errors: components["schemas"]["ApiErrorDetailDto"][] | null;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 500 */
                        code: number;
                        /** @example null */
                        data: null;
                        /** @example Internal server error */
                        message: string;
                        /** @example null */
                        errors: components["schemas"]["ApiErrorDetailDto"][] | null;
                    };
                };
            };
        };
    };
}
